name: Render readme

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt update && sudo apt -y install git

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # so we can commit --amend and push -f
          fetch-depth: 2

      - uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948 # v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          template: README.md.tpl
          writeTo: README.md

      - name: Commit changes
        run: |
          if ! git diff --quiet README.md; then
            git add README.md
            git commit --amend --no-edit
            git push --force
          fi
